### ISSUE TITLE
Middlewares broken?

### ISSUE THREAD

**Issue by vinzentt** [IsCoolEntertainment/titanium-request#9]
Hey,

when using the last dist/request.js my middlewares are not called anymore. Did sthg change?

Thanks.

**Comment by dawicorti** [comment]
I use middlewares with the latest request version. Can you bring an example please ?

**Comment by vinzentt** [comment]
Just by doing this: 
    var requestLib = require('ws/request');
    requestLib.use(function (req, res) {
            console.log('Middleware called');
    });
    requestLib.get('http://google.fr', function(){ console.log('google callback called');});
using my previous version(should be the one linked to my PR https://github.com/IsCoolEntertainment/titanium-request/pull/6), middleware is called, not with the last one.
I checked on android and ios.

**Comment by dawicorti** [comment]
Can you try with this new build please ?
